#Aponta para a porta onde o Ollama esta rodando
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

#Define o modelo que o Langchain4j vai utilizar do Ollama
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

#Define um timeout para a chamada
#Se o modelo demorar mais de 60s para responder a chamada irá falhar
quarkus.langchain4j.ollama.timeout=120s

#Escolhe o modelo de embedding para nosso Vector Database (Por default, caso essa prop venha sem falor, ela aponta pro NOMIC)
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

#A dimensão do vetor deve corresponder ao embedding-model, no caso o nomic possui 768 dimensões
#Confiugrando o PgVector para construir nosso VECTOR-DATABASE
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

# --- Configuração de Loggin da minha LLM pelo LangChang4j ---
# Loga a requisição completa enviada para a LLM (incluindo o manifesto de tools)
quarkus.langchain4j.log-requests=true

# Loga a resposta completa recebida do LLM (incluindo o manifesto de tools)
quarkus.langchain4j.log-responses=true

#Define um cliente chamado "booking-server"
quarkus.langchain4j.mcp.booking-server.transport-type=http
quarkus.langchain4j.mcp.booking-server.url=http://localhost:8081/mcp/sse/

#Timout generoso para garantir que o handshake com o microsserviço funcione
quarkus.langchain4j.mcp.booking-server.timout=30s

#Logs para ver o processo acontecendo
quarkus.langchain4j.mcp.booking-server.log-requests=true
quarkus.langchain4j.mcp.booking-server.log-responses=true