#Aponta para a porta onde o Ollama esta rodando
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

#Define o modelo que o Langchain4j vai utilizar do Ollama
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

#Define um timeout para a chamada
#Se o modelo demorar mais de 60s para responder a chamada irá falhar
quarkus.langchain4j.ollama.timeout=120s

#Escolhe o modelo de embedding para nosso Vector Database (Por default, caso essa prop venha sem falor, ela aponta pro NOMIC)
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text:latest

#A dimensão do vetor deve corresponder ao embedding-model, no caso o nomic possui 768 dimensões
#Confiugrando o PgVector para construir nosso VECTOR-DATABASE
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pgvector