#Aponta para a porta onde o Ollama esta rodando
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

#Define o modelo que o Langchain4j vai utilizar do Ollama
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

#Define um timeout para a chamada
#Se o modelo demorar mais de 60s para responder a chamada irá falhar
quarkus.langchain4j.ollama.timeout=120s

#Aponta para o diretório que contém nossos documentos
#O Easy RAG irá ler todos os arquivos neste local na inicialização
quarkus.langchain4j.easy-rag.path=src/main/resources/rag

#Reduz o tamanho dos chunks para criar chunks mais focados
quarkus.langchain4j.easy-rag.max-segment-size=100

#Cria um overlap de chunks para evitar perca de contexto
quarkus.langchain4j.easy-rag.max-overlap-size=20
